version: "3.9"

services:
  db:
    image: postgres:16
    container_name: finpilot_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: finpilot_user
      POSTGRES_PASSWORD: finpilot_pass
      POSTGRES_DB: finpilot
    ports:
      - "5432:5432"
    volumes:
      - finpilot_pgdata:/var/lib/postgresql/data

volumes:
  finpilot_pgdata:
